### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by efrapp**
This is a complete implementation of the Libray project. The feature branches were merged in this branch to show the application running with all the features required in the Odin Project.

### CODE REVIEW

**Review by rvvergara — CHANGES_REQUESTED** [review]
Hola @efrapp,

Los siento amigo. I didn't read the comment you made to my previous code review request. I don't normally see the Github emails soon enough. 

Anyhow, yeah I get it now. And good thing you merged all features here in `development` :) Though what you practiced (feature branches) is the right thing to do. Next time I'll consider that.

Ok there are just a few minor improvements I wanna suggest:

1. Our `addBookToLibrary.js` file is empty, we can safely delete it.
2. I raised #3 

Because of #3 above I am limited with what I can review. But here's an updated progress in our project checklist:

##### `New Book` button
- [x] It has a `New Book` button
- [x] It brings up a form
- [x] The form has an `author` field
- [x] The form has a `title` field
- [x] The form has a `number of pages` field
- [x] The form allows to mark the `Book` status as `read`

##### Display `Book`
- [x] It has a `render` function
- [x] It displays on the page every book contained in the array
- [x] Each `Book` displayed has a `button` to `remove` the `Book` from the `Library` array
- [x] Each `Book` displayed has a `button` to `toggle` the `Book` read status

### Crucial things to make project work

- [x] The project has a descriptive README.md
- [x] Keep the application logic separated from DOM manipulation tasks

The unchecked items I believe may be related to the issue and once that issue is fixed I can take a look at them :)

**Review by rvvergara — APPROVED** [review]
## Hi @efrapp,

Muchos gracias!! Now I can test the app.. 

### Awesome work on the UI -> It looks very sharp!

I just think that after I submitted the book form it should disappear. 

### Project checklist complete

As you will see in the previous checklist, every item is good!

So with this:

# :+1: 

## PS: Great job working with webpack on this one!! You demonstrated good understanding of modules here

**Comment by efrapp** [comment]
Thanks a lot @rvvergara! I need to be honest with you because I didn't know that all these things with modules were related to Webpack. The credit is yours because you pushed me to do the things in the right way!

**Comment by rvvergara** [comment]
> Thanks a lot @rvvergara! I need to be honest with you because I didn't know that all these things with modules were related to Webpack. The credit is yours because you pushed me to do the things in the right way!

You're welcome! We all learn new things. It's very admirable on your part to be open to new knowledge! I was in the same stage before and still am. I wish all who are learning software development had such an attitude

**Comment by efrapp** [comment]
Thank you Ryan, you are very kind. My goal is to improve every day.

**Pull request merged**
